---
title: Мисливці за привидами
hero_image: images/ghostbusters.png
description: Зробіть гру про полювання на привидів!
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-11-01
steps:
  - 
    title: Вступ
  - 
    title: Animate a ghost
  - 
    title: Random ghosts
  - 
    title: 'Challenge: more randomness'
    challenge: true
  - 
    title: Code for catching ghosts
  - 
    title: 'Challenge: add a sound'
    challenge: true
  - 
    title: Add a score
  - 
    title: Додати таймер
  - 
    title: 'Виклик: більше спрайтів'
    challenge: true
  - 
    title: Що далі?
