---
title: Ghostbusters
hero_image: images/ghostbusters.png
description: Make a game about catching ghosts!
listed: true
copyedit: true
version: 4.0.0
last_tested: 2018-10-11
steps:
  - title: Introduction
  - title: Animating a ghost
  - title: Random ghosts
  - title: Catching ghosts
  - title: Adding a score
  - title: Adding a timer
  - title: 'Challenge: more objects'
    challenge: true
