---
title: Ghostbusters
hero_image: images / ghostbusters.png
description: Tạo trò chơi về bắt bóng ma!
original_url: https://www.codeclubprojects.org/en-GB/scratch/ghostbusters
theme: màu xanh lá
listed: true
copyedit: true
ingredient: false
duration: 2
curriculum: 1, thiết kế-0, lập trình-1, phys-comp-0, sản xuất-0, cộng đồng-0
interests: Trò chơi
technologies: vết trầy
site_areas: dự án
hardware: ''
software: vết trầy
version: 4.0.1
last_tested: 2018-01-01
steps:
  - 
    title: Giới thiệu
  - 
    title: Những gì bạn cần
  - 
    title: Hoạt hình một con ma
  - 
    title: Bóng ma ngẫu nhiên
  - 
    title: Bắt ma
  - 
    title: Thêm điểm
  - 
    title: Thêm bộ hẹn giờ
  - 
    title: 'Thách thức: nhiều đối tượng hơn'
