---
title: Ghostbusters
hero_image: images / ghostbusters.png
description: Tạo trò chơi về bắt bóng ma!
original_url: https://www.codeclubprojects.org/en-GB/scratch/ghostbusters
theme: màu xanh lá
listed: true
copyedit: true
ingredient: false
duration: 2
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: Trò chơi
technologies: vết trầy
site_areas: projects
hardware: ''
software: vết trầy
version: 4.2
last_tested: 2018-01-01
steps:
  - 
    title: Giới thiệu
  - 
    title: Animating a ghost
  - 
    title: Random ghosts
  - 
    title: Catching ghosts
  - 
    title: Adding a score
  - 
    title: Adding a timer
  - 
    title: 'Thách thức: nhiều đối tượng hơn'
