---
title: Ghostbusters
hero_image: images / ghostbusters.png
description: Ulduzları tutmaq haqqında bir oyun edin!
original_url: https://www.codeclubprojects.org/en-GB/scratch/ghostbusters
theme: yaşıl
listed: true
copyedit: true
ingredient: false
duration: 2
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: oyunlar
technologies: cızıq
site_areas: projects
hardware: ''
software: scratch
version: 4.0.1
last_tested: 2018-01-01
steps:
  - 
    title: Giriş
  - 
    title: Nə lazımdırsın
  - 
    title: Bir hayaletin canlandırılması
  - 
    title: Random Ghosts
  - 
    title: Ulduzları tutmaq
  - 
    title: Hesab əlavə et
  - 
    title: Taymeri əlavə etmək
  - 
    title: 'Çağırış: daha çox obyekt'
