---
title: Cazafantasmas
hero_image: images/ghostbusters.png
description: ¡Aprende a crear un juego caza-fantasmas!
original_url: https://projects.raspberrypi.org/en/projects/ghostbusters
theme: green
listed: true
copyedit: true
ingredient: false
duration: 2
curriculum: builder, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: games
technologies: scratch
site_areas: codeclub, scratch
steps:
- title: Introducción
- title: Animar un fantasma
- title: Fantasmas aleatorios
- title: Cazar fantasmas
- title: Añadir puntuación
- title: Añadir un cronómetro
- title: "Desafío: Más objetos"

