---
title: Cazafantasmas
hero_image: images/ghostbusters.png
description: '¡Haz un juego sobre atrapar fantasmas!'
original_url: https://www.codeclubprojects.org/en-GB/scratch/ghostbusters
theme: verde
listed: true
copyedit: true
ingredient: false
duration: 2
curriculum: 1, diseño-0, programación-1, phys-comp-0, fabricación-0, comunidad-0
interests: juegos
technologies: scratch
site_areas: proyectos
hardware: ''
software: scratch
version: 4.2.1
last_tested: 2018-01-01
steps:
  - 
    title: Introducción
  - 
    title: Animando un fantasma
  - 
    title: Fantasmas aleatorios
  - 
    title: Atrapando fantasmas
  - 
    title: Añadir una puntuación
  - 
    title: Añadir un temporizador
  - 
    title: 'Desafío: más objetos'
    challenge: true
