---
title: Ghostbusters
hero_image: images/ghostbusters.png
description: Make a game about catching ghosts!
original_url: https://www.codeclubprojects.org/en-GB/scratch/ghostbusters
theme: green
listed: true
copyedit: true
ingredient: false
duration: 2
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4.2.1
last_tested: 2018-01-01
steps:
  - 
    title: Introduction
  - 
    title: Fantoma animată
  - 
    title: Fantome la întâmplare
  - 
    title: Prinde fantoma
  - 
    title: Adăugarea unui scor
  - 
    title: Adăugarea unui cronometru
  - 
    title: 'Provocare: mai multe obiecte'
    challenge: true
