---
title: Caça-fantasmas
hero_image: images/ghostbusters.png
description: Criar um jogo de caça-fantasmas!
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-11-01
steps:
  - 
    title: Introduction
  - 
    title: Animando um fantasma
  - 
    title: Random ghosts
  - 
    title: 'Desafio: mais aleatoriedade'
    challenge: true
  - 
    title: Código para capturar fantasmas
  - 
    title: 'Desafio: adicionar um som'
    challenge: true
  - 
    title: Adicionar uma pontuação
  - 
    title: Adicionar um cronômetro
  - 
    title: 'Desafio: Mais fantasmas'
    challenge: true
  - 
    title: What next?
