---
title: Ghostbusters
hero_image: imej / ghostbusters.png
description: Buat permainan tentang menangkap hantu!
original_url: https://www.codeclubprojects.org/en-GB/scratch/ghostbusters
theme: hijau
listed: true
copyedit: true
ingredient: false
duration: 2
curriculum: 1, reka bentuk-0, pengaturcaraan-1, phys-comp-0, pembuatan-0, komuniti-0
interests: permainan
technologies: awal
site_areas: projek
hardware: ''
software: awal
version: 4.0.1
last_tested: 2018-01-01
steps:
  - 
    title: Pengenalan
  - 
    title: Apa yang anda perlukan
  - 
    title: Animasi hantu
  - 
    title: Hantu rawak
  - 
    title: Menangkap hantu
  - 
    title: Menambah skor
  - 
    title: Menambah pemasa
  - 
    title: 'Cabaran: lebih banyak objek'
