---
title: Ghostbusters
hero_image: images/ghostbusters.png
description: Impara a creare un gioco di acchiappa fantasmi!
original_url: https://projects.raspberrypi.org/en/projects/ghostbusters
theme: green
listed: true
copyedit: true
ingredient: false
duration: 2
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4
last_tested: 2018-01-01
steps: 
- title: Introduzione
- title: Animare un fantasma
- title: Fantasmi a caso
- title: Acchiappare i fantasmi
- title: Aggiungi un punteggio
- title: Aggiungere un timer
- title: "Sfida: Altri oggetti"