---
title: Ghostbusters
hero_image: images / ghostbusters.png
description: Hayaletleri yakalamak hakkında bir oyun yapın!
original_url: https://www.codeclubprojects.org/en-GB/scratch/ghostbusters
theme: yeşil
listed: true
copyedit: true
ingredient: false
duration: 2
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: oyunlar
technologies: çizik
site_areas: projects
hardware: ''
software: scratch
version: 4.0.1
last_tested: 2018-01-01
steps:
  - 
    title: Giriş
  - 
    title: Neye ihtiyacınız olacak?
  - 
    title: Bir hayaleti canlandırmak
  - 
    title: Rastgele hayaletler
  - 
    title: Hayaletler yakalamak
  - 
    title: Bir skor ekleme
  - 
    title: Bir zamanlayıcı eklemek
  - 
    title: 'Zorluk: Daha fazla nesne'
